// Banque de questions — prototype (étape 1)
// culture : a = index de la bonne réponse dans c ; d = difficulté (1 facile, 2 moyen, 3 difficile)
// estimation : a = bonne réponse (nombre), u = unité affichée
var QUESTIONS = {
  culture: [
    { id: 'cg001', d: 1, q: "Quel est le nom de famille de Mario, le plombier de Nintendo ?", c: ["Mario", "Rossi", "Bros", "Luigi"], a: 0 },
    { id: 'cg002', d: 2, q: "Combien de cœurs a une pieuvre ?", c: ["1", "2", "3", "8"], a: 2 },
    { id: 'cg003', d: 2, q: "Dans Friends, comment s'appelle le singe de Ross ?", c: ["George", "Marcel", "Bobo", "Félix"], a: 1 },
    { id: 'cg004', d: 3, q: "Le croissant descend d'une viennoiserie venue de quel pays ?", c: ["Belgique", "Suisse", "Autriche", "Italie"], a: 2 },
    { id: 'cg005', d: 2, q: "Quelle planète tourne quasiment couchée sur le côté ?", c: ["Neptune", "Saturne", "Mars", "Uranus"], a: 3 },
    { id: 'cg006', d: 3, q: "Pour un botaniste, lequel de ces fruits est une baie ?", c: ["La fraise", "La banane", "La framboise", "La cerise"], a: 1 },
    { id: 'cg007', d: 1, q: "Combien de temps met la lumière du Soleil pour arriver jusqu'à nous ?", c: ["8 secondes", "8 minutes", "8 heures", "Instantanément"], a: 1 },
    { id: 'cg008', d: 2, q: "Quel est le seul mammifère capable de vraiment voler ?", c: ["L'écureuil volant", "Le colugo", "La chauve-souris", "Le phalanger volant"], a: 2 },
    { id: 'cg009', d: 2, q: "Dans quel pays se trouve Tombouctou ?", c: ["Niger", "Mali", "Mauritanie", "Tchad"], a: 1 },
    { id: 'cg010', d: 1, q: "Quelle langue parle-t-on au Brésil ?", c: ["Espagnol", "Brésilien", "Portugais", "Anglais"], a: 2 },
    { id: 'cg011', d: 1, q: "Quelle entreprise a créé Sonic le hérisson ?", c: ["Nintendo", "Sega", "Sony", "Atari"], a: 1 },
    { id: 'cg012', d: 1, q: "Quelle forme prend le patronus d'Harry Potter ?", c: ["Un loup", "Un cerf", "Un hibou", "Une biche"], a: 1 },
    { id: 'cg013', d: 3, q: "Quel est le plus grand désert du monde ?", c: ["Le Sahara", "Le Gobi", "L'Antarctique", "Le Kalahari"], a: 2 },
    { id: 'cg014', d: 2, q: "Quel organe humain est capable de se régénérer en partie ?", c: ["Le cœur", "Le foie", "Le cerveau", "Le pancréas"], a: 1 },
    { id: 'cg015', d: 1, q: "Combien de joueurs par équipe sur le terrain au rugby à XV ?", c: ["13", "11", "15", "16"], a: 2 },
    { id: 'cg016', d: 2, q: "Quel est le pays le plus peuplé du monde depuis 2023 ?", c: ["La Chine", "L'Inde", "Les États-Unis", "L'Indonésie"], a: 1 },
    { id: 'cg017', d: 3, q: "Le « wasabi » servi dans la plupart des restos est surtout fait de…", c: ["Wasabi", "Gingembre", "Raifort", "Avocat"], a: 2 },
    { id: 'cg018', d: 1, q: "Combien de dents a un adulte, dents de sagesse comprises ?", c: ["28", "30", "32", "36"], a: 2 },
    { id: 'cg019', d: 2, q: "Quel aliment a-t-on retrouvé encore comestible dans des tombes égyptiennes ?", c: ["Du pain", "Du miel", "Du fromage", "Des dattes"], a: 1 },
    { id: 'cg020', d: 2, q: "Quelle ville accueille les Jeux olympiques d'été de 2028 ?", c: ["Brisbane", "Madrid", "Los Angeles", "Rome"], a: 2 },
    { id: 'cg021', d: 3, q: "Dans Le Seigneur des anneaux, combien d'anneaux ont été donnés aux Nains ?", c: ["Trois", "Sept", "Neuf", "Un seul"], a: 1 },
    { id: 'cg022', d: 1, q: "Lequel de ces animaux peut dormir debout ?", c: ["Le cheval", "Le chat", "Le chien", "Le lapin"], a: 0 },
    { id: 'cg023', d: 1, q: "Quel est le symbole chimique de l'or ?", c: ["Or", "Ag", "Au", "Go"], a: 2 },
    { id: 'cg024', d: 1, q: "Quel réseau social avait un oiseau bleu pour logo avant de devenir X ?", c: ["Bluesky", "Twitter", "Threads", "Telegram"], a: 1 },
    { id: 'cg025', d: 1, q: "Combien de cases compte un échiquier ?", c: ["49", "64", "81", "100"], a: 1 },
    { id: 'cg026', d: 1, q: "Quel jeu vidéo se déroule dans la ville de Los Santos ?", c: ["Watch Dogs", "Red Dead Redemption 2", "GTA V", "Mafia"], a: 2 },
    { id: 'cg027', d: 3, q: "Quel pays compte le plus de fuseaux horaires, territoires d'outre-mer compris ?", c: ["La Russie", "Les États-Unis", "La France", "La Chine"], a: 2 },
    { id: 'cg028', d: 2, q: "Quelle est la capitale de l'Australie ?", c: ["Sydney", "Melbourne", "Canberra", "Perth"], a: 2 },
    { id: 'cg029', d: 2, q: "Dans quel épisode de Star Wars entend-on « Je suis ton père » ?", c: ["Un nouvel espoir", "L'Empire contre-attaque", "Le Retour du Jedi", "La Menace fantôme"], a: 1 },
    { id: 'cg030', d: 1, q: "Quel est le plus petit pays du monde ?", c: ["Monaco", "Saint-Marin", "Le Vatican", "Malte"], a: 2 },
    { id: 'cg031', d: 2, q: "Pourquoi les flamants roses sont-ils roses ?", c: ["Leurs gènes", "Leur alimentation", "Le soleil", "L'eau salée"], a: 1 },
    { id: 'cg032', d: 1, q: "Qui a peint La Nuit étoilée ?", c: ["Claude Monet", "Edvard Munch", "Vincent van Gogh", "Paul Gauguin"], a: 2 },
    { id: 'cg033', d: 2, q: "Quel est l'os le plus long du corps humain ?", c: ["Le tibia", "Le fémur", "L'humérus", "Le péroné"], a: 1 },
    { id: 'cg034', d: 2, q: "Dans quelle ville se trouve la Sagrada Família ?", c: ["Madrid", "Séville", "Barcelone", "Valence"], a: 2 },
    { id: 'cg035', d: 3, q: "Quel animal a des empreintes digitales presque identiques aux nôtres ?", c: ["Le koala", "La loutre", "Le raton laveur", "Le panda"], a: 0 },
    { id: 'cg036', d: 2, q: "Combien de joueurs s'affrontent au départ d'une partie classique de Fortnite ?", c: ["50", "64", "100", "150"], a: 2 }
  ],
  estimation: [
    { id: 'es001', q: "En quelle année est sorti le premier iPhone ?", a: 2007, u: "" },
    { id: 'es002', q: "Combien mesure la tour Eiffel, antennes comprises ?", a: 330, u: "mètres" },
    { id: 'es003', q: "Combien d'os compte le squelette d'un adulte ?", a: 206, u: "os" },
    { id: 'es004', q: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", a: 1969, u: "" },
    { id: 'es005', q: "Combien mesure le tour de la Terre à l'équateur ?", a: 40075, u: "km" },
    { id: 'es006', q: "Combien de pays font partie de l'Union européenne ?", a: 27, u: "pays" },
    { id: 'es007', q: "Combien de touches compte un piano classique ?", a: 88, u: "touches" },
    { id: 'es008', q: "Quelle est l'altitude du mont Blanc ?", a: 4806, u: "mètres" },
    { id: 'es009', q: "Combien d'épisodes compte la série Friends au total ?", a: 236, u: "épisodes" },
    { id: 'es010', q: "En quelle année est sorti le premier Toy Story au cinéma ?", a: 1995, u: "" },
    { id: 'es011', q: "Combien de litres de sang circulent dans le corps d'un adulte ?", a: 5, u: "litres" },
    { id: 'es012', q: "À quelle vitesse maximale court un guépard ?", a: 110, u: "km/h" },
    { id: 'es013', q: "Quelle distance sépare Paris de Marseille à vol d'oiseau ?", a: 660, u: "km" },
    { id: 'es014', q: "En quelle année Facebook a-t-il été créé ?", a: 2004, u: "" },
    { id: 'es015', q: "Combien de pays sont membres de l'ONU ?", a: 193, u: "pays" },
    { id: 'es016', q: "Combien d'habitants compte la France ?", a: 68, u: "millions" },
    { id: 'es017', q: "Combien de minutes dure le film Titanic ?", a: 194, u: "minutes" },
    { id: 'es018', q: "Quelle est la profondeur de la fosse des Mariannes, le point le plus profond des océans ?", a: 10935, u: "mètres" },
    { id: 'es019', q: "En quelle année la première PlayStation est-elle sortie au Japon ?", a: 1994, u: "" },
    { id: 'es020', q: "Combien de cartes compte un jeu de tarot ?", a: 78, u: "cartes" }
  ]
};
