// Banque de questions — prototype (étape 1)
// culture : a = index de la bonne réponse dans c ; d = difficulté (1 facile, 2 moyen, 3 difficile)
// estimation : a = bonne réponse (nombre), u = unité affichée
var QUESTIONS = {
  culture: [
    { id: 'cg001', d: 1, q: "Quel est le nom de famille de Mario, le plombier de Nintendo ?", c: ["Mario", "Rossi", "Bros", "Luigi"], a: 0 },
    { id: 'cg002', d: 2, q: "Combien de cœurs a une pieuvre ?", c: ["1", "2", "3", "8"], a: 2 },
    { id: 'cg003', d: 2, q: "Dans Friends, comment s'appelle le singe de Ross ?", c: ["George", "Marcel", "Bobo", "Félix"], a: 1 },
    { id: 'cg004', d: 3, q: "Le croissant descend d'une viennoiserie venue de quel pays ?", c: ["Belgique", "Suisse", "Autriche", "Italie"], a: 2 },
    { id: 'cg005', d: 2, q: "Quelle planète tourne quasiment couchée sur le côté ?", c: ["Neptune", "Saturne", "Mars", "Uranus"], a: 3 },
    { id: 'cg006', d: 3, q: "Pour un botaniste, lequel de ces fruits est une baie ?", c: ["La fraise", "La banane", "La framboise", "La cerise"], a: 1 },
    { id: 'cg007', d: 1, q: "Combien de temps met la lumière du Soleil pour arriver jusqu'à nous ?", c: ["8 secondes", "8 minutes", "8 heures", "Instantanément"], a: 1 },
    { id: 'cg008', d: 2, q: "Quel est le seul mammifère capable de vraiment voler ?", c: ["L'écureuil volant", "Le colugo", "La chauve-souris", "Le phalanger volant"], a: 2 },
    { id: 'cg009', d: 2, q: "Dans quel pays se trouve Tombouctou ?", c: ["Niger", "Mali", "Mauritanie", "Tchad"], a: 1 },
    { id: 'cg010', d: 1, q: "Quelle langue parle-t-on au Brésil ?", c: ["Espagnol", "Brésilien", "Portugais", "Anglais"], a: 2 },
    { id: 'cg011', d: 1, q: "Quelle entreprise a créé Sonic le hérisson ?", c: ["Nintendo", "Sega", "Sony", "Atari"], a: 1 },
    { id: 'cg012', d: 1, q: "Quelle forme prend le patronus d'Harry Potter ?", c: ["Un loup", "Un cerf", "Un hibou", "Une biche"], a: 1 },
    { id: 'cg013', d: 3, q: "Quel est le plus grand désert du monde ?", c: ["Le Sahara", "Le Gobi", "L'Antarctique", "Le Kalahari"], a: 2 },
    { id: 'cg014', d: 2, q: "Quel organe humain est capable de se régénérer en partie ?", c: ["Le cœur", "Le foie", "Le cerveau", "Le pancréas"], a: 1 },
    { id: 'cg015', d: 1, q: "Combien de joueurs par équipe sur le terrain au rugby à XV ?", c: ["13", "11", "15", "16"], a: 2 },
    { id: 'cg016', d: 2, q: "Quel est le pays le plus peuplé du monde depuis 2023 ?", c: ["La Chine", "L'Inde", "Les États-Unis", "L'Indonésie"], a: 1 },
    { id: 'cg017', d: 3, q: "Le « wasabi » servi dans la plupart des restos est surtout fait de…", c: ["Wasabi", "Gingembre", "Raifort", "Avocat"], a: 2 },
    { id: 'cg018', d: 1, q: "Combien de dents a un adulte, dents de sagesse comprises ?", c: ["28", "30", "32", "36"], a: 2 },
    { id: 'cg019', d: 2, q: "Quel aliment a-t-on retrouvé encore comestible dans des tombes égyptiennes ?", c: ["Du pain", "Du miel", "Du fromage", "Des dattes"], a: 1 },
    { id: 'cg020', d: 2, q: "Quelle ville accueille les Jeux olympiques d'été de 2028 ?", c: ["Brisbane", "Madrid", "Los Angeles", "Rome"], a: 2 },
    { id: 'cg021', d: 3, q: "Dans Le Seigneur des anneaux, combien d'anneaux ont été donnés aux Nains ?", c: ["Trois", "Sept", "Neuf", "Un seul"], a: 1 },
    { id: 'cg022', d: 1, q: "Lequel de ces animaux peut dormir debout ?", c: ["Le cheval", "Le chat", "Le chien", "Le lapin"], a: 0 },
    { id: 'cg023', d: 1, q: "Quel est le symbole chimique de l'or ?", c: ["Or", "Ag", "Au", "Go"], a: 2 },
    { id: 'cg024', d: 1, q: "Quel réseau social avait un oiseau bleu pour logo avant de devenir X ?", c: ["Bluesky", "Twitter", "Threads", "Telegram"], a: 1 },
    { id: 'cg025', d: 1, q: "Combien de cases compte un échiquier ?", c: ["49", "64", "81", "100"], a: 1 },
    { id: 'cg026', d: 1, q: "Quel jeu vidéo se déroule dans la ville de Los Santos ?", c: ["Watch Dogs", "Red Dead Redemption 2", "GTA V", "Mafia"], a: 2 },
    { id: 'cg027', d: 3, q: "Quel pays compte le plus de fuseaux horaires, territoires d'outre-mer compris ?", c: ["La Russie", "Les États-Unis", "La France", "La Chine"], a: 2 },
    { id: 'cg028', d: 2, q: "Quelle est la capitale de l'Australie ?", c: ["Sydney", "Melbourne", "Canberra", "Perth"], a: 2 },
    { id: 'cg029', d: 2, q: "Dans quel épisode de Star Wars entend-on « Je suis ton père » ?", c: ["Un nouvel espoir", "L'Empire contre-attaque", "Le Retour du Jedi", "La Menace fantôme"], a: 1 },
    { id: 'cg030', d: 1, q: "Quel est le plus petit pays du monde ?", c: ["Monaco", "Saint-Marin", "Le Vatican", "Malte"], a: 2 },
    { id: 'cg031', d: 2, q: "Pourquoi les flamants roses sont-ils roses ?", c: ["Leurs gènes", "Leur alimentation", "Le soleil", "L'eau salée"], a: 1 },
    { id: 'cg032', d: 1, q: "Qui a peint La Nuit étoilée ?", c: ["Claude Monet", "Edvard Munch", "Vincent van Gogh", "Paul Gauguin"], a: 2 },
    { id: 'cg033', d: 2, q: "Quel est l'os le plus long du corps humain ?", c: ["Le tibia", "Le fémur", "L'humérus", "Le péroné"], a: 1 },
    { id: 'cg034', d: 2, q: "Dans quelle ville se trouve la Sagrada Família ?", c: ["Madrid", "Séville", "Barcelone", "Valence"], a: 2 },
    { id: 'cg035', d: 3, q: "Quel animal a des empreintes digitales presque identiques aux nôtres ?", c: ["Le koala", "La loutre", "Le raton laveur", "Le panda"], a: 0 },
    { id: 'cg036', d: 2, q: "Combien de joueurs s'affrontent au départ d'une partie classique de Fortnite ?", c: ["50", "64", "100", "150"], a: 2 }
  ],
  estimation: [
    { id: 'es001', q: "En quelle année est sorti le premier iPhone ?", a: 2007, u: "" },
    { id: 'es002', q: "Combien mesure la tour Eiffel, antennes comprises ?", a: 330, u: "mètres" },
    { id: 'es003', q: "Combien d'os compte le squelette d'un adulte ?", a: 206, u: "os" },
    { id: 'es004', q: "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", a: 1969, u: "" },
    { id: 'es005', q: "Combien mesure le tour de la Terre à l'équateur ?", a: 40075, u: "km" },
    { id: 'es006', q: "Combien de pays font partie de l'Union européenne ?", a: 27, u: "pays" },
    { id: 'es007', q: "Combien de touches compte un piano classique ?", a: 88, u: "touches" },
    { id: 'es008', q: "Quelle est l'altitude du mont Blanc ?", a: 4806, u: "mètres" },
    { id: 'es009', q: "Combien d'épisodes compte la série Friends au total ?", a: 236, u: "épisodes" },
    { id: 'es010', q: "En quelle année est sorti le premier Toy Story au cinéma ?", a: 1995, u: "" },
    { id: 'es011', q: "Combien de litres de sang circulent dans le corps d'un adulte ?", a: 5, u: "litres" },
    { id: 'es012', q: "À quelle vitesse maximale court un guépard ?", a: 110, u: "km/h" },
    { id: 'es013', q: "Quelle distance sépare Paris de Marseille à vol d'oiseau ?", a: 660, u: "km" },
    { id: 'es014', q: "En quelle année Facebook a-t-il été créé ?", a: 2004, u: "" },
    { id: 'es015', q: "Combien de pays sont membres de l'ONU ?", a: 193, u: "pays" },
    { id: 'es016', q: "Combien d'habitants compte la France ?", a: 68, u: "millions" },
    { id: 'es017', q: "Combien de minutes dure le film Titanic ?", a: 194, u: "minutes" },
    { id: 'es018', q: "Quelle est la profondeur de la fosse des Mariannes, le point le plus profond des océans ?", a: 10935, u: "mètres" },
    { id: 'es019', q: "En quelle année la première PlayStation est-elle sortie au Japon ?", a: 1994, u: "" },
    { id: 'es020', q: "Combien de cartes compte un jeu de tarot ?", a: 78, u: "cartes" }
  ]
  ,
  // bluff : a = la vraie réponse ; alt = autres façons de l'écrire (pour reconnaître la vérité tapée par erreur)
  bluff: [
    { id: 'bl001', q: "Quel est l'animal national de l'Écosse ?", a: "La licorne", alt: ["licorne", "une licorne"] },
    { id: 'bl002', q: "Que veut dire l'adjectif « callipyge » ?", a: "Qui a de belles fesses", alt: ["belles fesses", "beau fessier", "jolies fesses"] },
    { id: 'bl003', q: "Qu'est-ce que le « philtrum » ?", a: "Le creux entre le nez et la lèvre", alt: ["creux entre le nez et la levre", "creux au dessus de la levre", "sillon sous le nez"] },
    { id: 'bl004', q: "Qu'est-ce que la « glabelle » ?", a: "L'espace entre les deux sourcils", alt: ["entre les sourcils", "espace entre les sourcils"] },
    { id: 'bl005', q: "Qu'est-ce qu'un « ferret » ?", a: "L'embout au bout d'un lacet", alt: ["bout du lacet", "embout du lacet", "embout de lacet"] },
    { id: 'bl006', q: "Qu'est-ce que le « pétrichor » ?", a: "L'odeur de la terre après la pluie", alt: ["odeur apres la pluie", "odeur de la pluie", "odeur de terre mouillee"] },
    { id: 'bl007', q: "Que signifie le mot « sérendipité » ?", a: "Une heureuse découverte due au hasard", alt: ["decouverte par hasard", "trouver par hasard", "hasard heureux"] },
    { id: 'bl008', q: "Que fait un « vexillologue » ?", a: "Il étudie les drapeaux", alt: ["etudie les drapeaux", "specialiste des drapeaux", "drapeaux"] },
    { id: 'bl009', q: "Qu'est-ce qu'un « phosphène » ?", a: "Les taches lumineuses quand on se frotte les yeux", alt: ["taches lumineuses", "lumieres quand on se frotte les yeux", "points lumineux yeux fermes"] },
    { id: 'bl010', q: "Qu'est-ce que la « lunule » ?", a: "Le croissant blanc à la base de l'ongle", alt: ["blanc de l'ongle", "croissant blanc de l'ongle", "zone blanche de l'ongle"] },
    { id: 'bl011', q: "Qu'est-ce qu'un « gnomon » ?", a: "La tige d'un cadran solaire", alt: ["tige du cadran solaire", "aiguille du cadran solaire", "cadran solaire"] },
    { id: 'bl012', q: "Qu'est-ce que la « pandiculation » ?", a: "S'étirer en bâillant", alt: ["etirer en baillant", "s'etirer et bailler", "etirement en baillant"] },
    { id: 'bl013', q: "Qu'est-ce que la « tachyphagie » ?", a: "Le fait de manger trop vite", alt: ["manger trop vite", "manger vite"] },
    { id: 'bl014', q: "De quoi a peur une personne atteinte d'« hippopotomonstrosesquippedaliophobie » ?", a: "Des mots trop longs", alt: ["mots longs", "longs mots", "peur des mots longs"] },
    { id: 'bl015', q: "Que fait un « dendrochronologue » ?", a: "Il date les arbres grâce à leurs cernes", alt: ["date les arbres", "age des arbres", "compte les cernes des arbres"] },
    { id: 'bl016', q: "Qu'est-ce que le « tragus » ?", a: "Le petit cartilage devant l'oreille", alt: ["cartilage de l'oreille", "bout de l'oreille", "petit bout devant l'oreille"] },
    { id: 'bl017', q: "Qu'est-ce qu'un « sycophante » ?", a: "Un dénonciateur", alt: ["delateur", "denonciateur", "balance", "mouchard"] },
    { id: 'bl018', q: "Que désigne l'« ultracrépidarianisme » ?", a: "Parler de ce qu'on ne connaît pas", alt: ["parler de ce qu'on ne connait pas", "avis sur tout", "donner son avis sans savoir"] },
    { id: 'bl019', q: "Que veut dire le verbe « s'esbaudir » ?", a: "Se réjouir bruyamment", alt: ["se rejouir", "s'emerveiller", "se rejouir bruyamment"] },
    { id: 'bl020', q: "Que veut dire « borborygme » ?", a: "Un gargouillis du ventre", alt: ["gargouillis", "bruit du ventre", "gargouillement"] },
    { id: 'bl021', q: "Le mot « muscle » vient d'un mot latin qui désignait quel animal ?", a: "La souris", alt: ["souris", "petite souris"] },
    { id: 'bl022', q: "Avant l'invention de la gomme, avec quoi effaçait-on le crayon ?", a: "De la mie de pain", alt: ["mie de pain", "pain"] },
    { id: 'bl023', q: "À quoi servait la pâte à modeler Play-Doh à l'origine ?", a: "À nettoyer le papier peint", alt: ["nettoyer le papier peint", "nettoyant papier peint", "nettoyer les murs"] },
    { id: 'bl024', q: "Combien de temps a duré la guerre la plus courte de l'histoire ?", a: "38 minutes", alt: ["38 min", "trente-huit minutes", "moins d'une heure"] },
    { id: 'bl025', q: "Dans quel pays a été inventée la pizza hawaïenne ?", a: "Au Canada", alt: ["canada"] },
    { id: 'bl026', q: "De quelle couleur étaient le plus souvent les carottes avant le XVIIᵉ siècle ?", a: "Violettes", alt: ["violet", "violette", "pourpre"] },
    { id: 'bl027', q: "À l'origine, le Coca-Cola était vendu comme…", a: "Un médicament", alt: ["medicament", "remede", "un remede", "sirop contre la fatigue"] },
    { id: 'bl028', q: "En combien de compartiments est divisé l'estomac d'une vache ?", a: "Quatre", alt: ["4", "quatre compartiments", "4 poches"] },
    { id: 'bl029', q: "Qu'a inventé l'actrice hollywoodienne Hedy Lamarr ?", a: "L'ancêtre du Wi-Fi et du Bluetooth", alt: ["wifi", "bluetooth", "saut de frequence", "ancetre du wifi"] },
    { id: 'bl030', q: "Quel métier exerçait Harrison Ford avant de devenir Han Solo ?", a: "Charpentier", alt: ["menuisier", "charpentier menuisier"] },
    { id: 'bl031', q: "Quel animal a été jugé et pendu en Normandie en 1386 ?", a: "Un cochon", alt: ["cochon", "une truie", "truie", "porc"] },
    { id: 'bl032', q: "Quel animal fait des crottes en forme de cube ?", a: "Le wombat", alt: ["wombat"] },
    { id: 'bl033', q: "À quoi devait servir le papier bulle à son invention ?", a: "Du papier peint", alt: ["papier peint", "tapisserie", "decoration murale"] },
    { id: 'bl034', q: "Que vendait Nintendo à sa création en 1889 ?", a: "Des cartes à jouer", alt: ["cartes a jouer", "cartes", "jeux de cartes"] },
    { id: 'bl035', q: "Que fabriquait Lamborghini avant les voitures de sport ?", a: "Des tracteurs", alt: ["tracteur", "tracteurs"] },
    { id: 'bl036', q: "Comment s'appelle le chat d'Hermione dans Harry Potter ?", a: "Pattenrond", alt: ["pattenrond", "patte en rond", "crookshanks"] },
    { id: 'bl037', q: "Que veut dire « Lego » en danois ?", a: "Joue bien", alt: ["jouer bien", "bien jouer", "joue bien"] },
    { id: 'bl038', q: "Que veut dire « wiki » en hawaïen ?", a: "Rapide", alt: ["vite", "rapidement"] },
    { id: 'bl039', q: "D'où vient le nom « Bluetooth » ?", a: "D'un roi viking à la dent bleue", alt: ["roi viking", "harald a la dent bleue", "dent bleue", "roi danois"] },
    { id: 'bl040', q: "Que voulait dire le mot tchèque « robota », d'où vient « robot » ?", a: "Corvée", alt: ["corvee", "travail force", "travail"] },
    { id: 'bl041', q: "Quel animal dort avec une moitié du cerveau éveillée ?", a: "Le dauphin", alt: ["dauphin"] },
    { id: 'bl042', q: "Combien de temps peut vivre la méduse Turritopsis dohrnii ?", a: "Pour toujours : elle rajeunit", alt: ["eternellement", "pour toujours", "infiniment", "immortelle"] }
  ],
  // ordre : items dans le BON ordre ; v = l'info affichée à la révélation
  ordre: [
    { id: 'or001', q: "Du plus ancien au plus récent", items: [{ t: "Pyramides de Gizeh", v: "vers 2560 av. J.-C." }, { t: "Colisée de Rome", v: "80" }, { t: "Notre-Dame de Paris", v: "1163 (début)" }, { t: "Tour Eiffel", v: "1889" }] },
    { id: 'or002', q: "Inventions, de la plus ancienne à la plus récente", items: [{ t: "Imprimerie de Gutenberg", v: "vers 1450" }, { t: "Téléphone", v: "1876" }, { t: "Télévision", v: "1926" }, { t: "World Wide Web", v: "1989" }] },
    { id: 'or003', q: "Planètes, de la plus grosse à la plus petite", items: [{ t: "Jupiter", v: "140 000 km" }, { t: "Saturne", v: "116 000 km" }, { t: "Terre", v: "12 700 km" }, { t: "Mars", v: "6 800 km" }] },
    { id: 'or004', q: "Pays, du plus peuplé au moins peuplé", items: [{ t: "Inde", v: "≈ 1,4 milliard" }, { t: "États-Unis", v: "≈ 340 millions" }, { t: "Brésil", v: "≈ 210 millions" }, { t: "France", v: "≈ 68 millions" }] },
    { id: 'or005', q: "Montagnes, de la plus haute à la moins haute", items: [{ t: "Everest", v: "8 849 m" }, { t: "K2", v: "8 611 m" }, { t: "Mont Blanc", v: "4 806 m" }, { t: "Mont Ventoux", v: "1 910 m" }] },
    { id: 'or006', q: "Du plus rapide au plus lent", items: [{ t: "Faucon pèlerin en piqué", v: "≈ 390 km/h" }, { t: "Guépard", v: "≈ 110 km/h" }, { t: "Cheval au galop", v: "≈ 70 km/h" }, { t: "Usain Bolt", v: "≈ 44 km/h" }] },
    { id: 'or007', q: "Consoles, de la plus ancienne à la plus récente", items: [{ t: "Game Boy", v: "1989" }, { t: "PlayStation", v: "1994" }, { t: "Wii", v: "2006" }, { t: "Nintendo Switch", v: "2017" }] },
    { id: 'or008', q: "Films, du plus ancien au plus récent", items: [{ t: "Le Roi lion", v: "1994" }, { t: "Titanic", v: "1997" }, { t: "Avatar", v: "2009" }, { t: "La Reine des neiges", v: "2013" }] },
    { id: 'or009', q: "Pays, du plus grand au plus petit", items: [{ t: "Russie", v: "17,1 M km²" }, { t: "Canada", v: "10 M km²" }, { t: "Brésil", v: "8,5 M km²" }, { t: "France", v: "0,55 M km²" }] },
    { id: 'or010', q: "Événements, du plus ancien au plus récent", items: [{ t: "Révolution française", v: "1789" }, { t: "Sacre de Napoléon", v: "1804" }, { t: "Début de la Première Guerre mondiale", v: "1914" }, { t: "Premier pas sur la Lune", v: "1969" }] },
    { id: 'or011', q: "Animaux, du plus lourd au plus léger", items: [{ t: "Baleine bleue", v: "≈ 150 t" }, { t: "Éléphant d'Afrique", v: "≈ 6 t" }, { t: "Girafe", v: "≈ 1,2 t" }, { t: "Lion", v: "≈ 190 kg" }] },
    { id: 'or012', q: "Réseaux sociaux, du plus ancien au plus récent", items: [{ t: "Facebook", v: "2004" }, { t: "YouTube", v: "2005" }, { t: "Instagram", v: "2010" }, { t: "TikTok", v: "2016" }] },
    { id: 'or013', q: "Villes françaises, de la plus peuplée à la moins peuplée", items: [{ t: "Paris", v: "≈ 2,1 millions" }, { t: "Marseille", v: "≈ 870 000" }, { t: "Lyon", v: "≈ 520 000" }, { t: "Nice", v: "≈ 350 000" }] },
    { id: 'or014', q: "Os, du plus long au plus court", items: [{ t: "Fémur", v: "≈ 48 cm" }, { t: "Tibia", v: "≈ 43 cm" }, { t: "Humérus", v: "≈ 36 cm" }, { t: "Radius", v: "≈ 25 cm" }] },
    { id: 'or015', q: "Livres Harry Potter, du premier au dernier publié", items: [{ t: "L'École des sorciers", v: "1997" }, { t: "La Chambre des secrets", v: "1998" }, { t: "La Coupe de feu", v: "2000" }, { t: "Les Reliques de la Mort", v: "2007" }] },
    { id: 'or016', q: "Océans, du plus grand au plus petit", items: [{ t: "Pacifique", v: "≈ 165 M km²" }, { t: "Atlantique", v: "≈ 106 M km²" }, { t: "Indien", v: "≈ 70 M km²" }, { t: "Arctique", v: "≈ 14 M km²" }] },
    { id: 'or017', q: "Planètes, de la plus chaude à la plus froide", items: [{ t: "Vénus", v: "≈ 460 °C" }, { t: "Mercure", v: "≈ 170 °C en moyenne" }, { t: "Terre", v: "≈ 15 °C" }, { t: "Mars", v: "≈ −60 °C" }] },
    { id: 'or018', q: "Inventions, de la plus ancienne à la plus récente", items: [{ t: "La roue", v: "vers 3500 av. J.-C." }, { t: "La boussole", v: "XIᵉ siècle" }, { t: "Les lunettes", v: "fin du XIIIᵉ siècle" }, { t: "La machine à vapeur", v: "XVIIIᵉ siècle" }] },
    { id: 'or019', q: "Bâtiments, du plus haut au moins haut", items: [{ t: "Burj Khalifa", v: "828 m" }, { t: "Shanghai Tower", v: "632 m" }, { t: "One World Trade Center", v: "541 m" }, { t: "Tour Eiffel", v: "330 m" }] },
    { id: 'or020', q: "Du plus de pattes au moins de pattes", items: [{ t: "Mille-pattes", v: "des dizaines, voire des centaines" }, { t: "Araignée", v: "8" }, { t: "Fourmi", v: "6" }, { t: "Chien", v: "4" }] },
    { id: 'or021', q: "Durée de vie, de la plus longue à la plus courte", items: [{ t: "Tortue géante", v: "> 100 ans" }, { t: "Humain", v: "≈ 80 ans" }, { t: "Chien", v: "≈ 13 ans" }, { t: "Hamster", v: "≈ 2 à 3 ans" }] },
    { id: 'or022', q: "Jeux olympiques d'été, du plus ancien au plus récent", items: [{ t: "Athènes", v: "1896" }, { t: "Berlin", v: "1936" }, { t: "Mexico", v: "1968" }, { t: "Paris", v: "2024" }] },
    { id: 'or023', q: "Personnages, du plus ancien au plus récent (naissance)", items: [{ t: "Léonard de Vinci", v: "1452" }, { t: "Molière", v: "1622" }, { t: "Victor Hugo", v: "1802" }, { t: "Albert Einstein", v: "1879" }] },
    { id: 'or024', q: "Du plus rapide au plus lent", items: [{ t: "La lumière", v: "300 000 km/s" }, { t: "Le son", v: "≈ 1 235 km/h" }, { t: "Record du TGV", v: "574,8 km/h" }, { t: "Usain Bolt", v: "≈ 44 km/h" }] },
    { id: 'or025', q: "Du plus grand volume au plus petit", items: [{ t: "Piscine olympique", v: "≈ 2 500 000 L" }, { t: "Baignoire", v: "≈ 200 L" }, { t: "Seau", v: "≈ 10 L" }, { t: "Verre d'eau", v: "≈ 0,2 L" }] },
    { id: 'or026', q: "Pays, du plus au nord au plus au sud", items: [{ t: "Norvège", v: "" }, { t: "Allemagne", v: "" }, { t: "Espagne", v: "" }, { t: "Maroc", v: "" }] },
    { id: 'or027', q: "Planètes, de la plus proche du Soleil à la plus lointaine", items: [{ t: "Mars", v: "4ᵉ" }, { t: "Jupiter", v: "5ᵉ" }, { t: "Saturne", v: "6ᵉ" }, { t: "Neptune", v: "8ᵉ" }] },
    { id: 'or028', q: "Jeux vidéo, du plus ancien au plus récent", items: [{ t: "Pac-Man", v: "1980" }, { t: "Tetris", v: "1984" }, { t: "Super Mario Bros.", v: "1985" }, { t: "Minecraft", v: "2009" }] },
    { id: 'or029', q: "Appareils, du plus ancien au plus récent", items: [{ t: "Walkman", v: "1979" }, { t: "Premier iPod", v: "2001" }, { t: "Premier iPhone", v: "2007" }, { t: "Premier iPad", v: "2010" }] },
    { id: 'or030', q: "Écrivains, du plus ancien au plus récent (naissance)", items: [{ t: "Jean de La Fontaine", v: "1621" }, { t: "Voltaire", v: "1694" }, { t: "Émile Zola", v: "1840" }, { t: "Albert Camus", v: "1913" }] }
  ]
};
